type: google.api.Service
config_version: 3

name: hello.endpoints.devision-io.cloud.goog

title: hello.api.devision.io
apis:
- name: helloapi.HelloService


usage:
  rules:
  - selector: "*"
    allow_unregistered_calls: true

authentication:
  providers:
  - id: google_service_account
    issuer: "token-issuer.devision.io"
    audiences: "apis.devision.io"
    jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/token-issuer@devision-io.iam.gserviceaccount.com"
  rules:
  - selector: "*"
    requirements:
      - provider_id: google_service_account