# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from v1 import hello_pb2 as v1_dot_hello__pb2


class HelloStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.unary_unary(
        '/devision.hello.v1.Hello/Echo',
        request_serializer=v1_dot_hello__pb2.EchoRequest.SerializeToString,
        response_deserializer=v1_dot_hello__pb2.EchoResponse.FromString,
        )
    self.Ping = channel.unary_unary(
        '/devision.hello.v1.Hello/Ping',
        request_serializer=v1_dot_hello__pb2.PingRequest.SerializeToString,
        response_deserializer=v1_dot_hello__pb2.PingResponse.FromString,
        )


class HelloServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Echo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.unary_unary_rpc_method_handler(
          servicer.Echo,
          request_deserializer=v1_dot_hello__pb2.EchoRequest.FromString,
          response_serializer=v1_dot_hello__pb2.EchoResponse.SerializeToString,
      ),
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=v1_dot_hello__pb2.PingRequest.FromString,
          response_serializer=v1_dot_hello__pb2.PingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'devision.hello.v1.Hello', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
