# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import abc
import concurrent.futures
import google.protobuf.message
import typing

class EchoRequest(google.protobuf.message.Message):
    name = ... # type: typing.Text

    def __init__(self,
        name : typing.Optional[typing.Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> EchoRequest: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class EchoResponse(google.protobuf.message.Message):
    server_id = ... # type: typing.Text
    name = ... # type: typing.Text

    def __init__(self,
        server_id : typing.Optional[typing.Text] = None,
        name : typing.Optional[typing.Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> EchoResponse: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class PingRequest(google.protobuf.message.Message):
    ping = ... # type: typing.Text

    def __init__(self,
        ping : typing.Optional[typing.Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> PingRequest: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class PingResponse(google.protobuf.message.Message):
    ping = ... # type: typing.Text

    def __init__(self,
        ping : typing.Optional[typing.Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> PingResponse: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class HelloService(typing.Any, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Echo(self,
        rpc_controller: typing.Any,
        request: EchoRequest,
        done: typing.Optional[typing.Callable[[EchoResponse], None]],
    ) -> concurrent.futures.Future[EchoResponse]: ...
    @abc.abstractmethod
    def Ping(self,
        rpc_controller: typing.Any,
        request: PingRequest,
        done: typing.Optional[typing.Callable[[PingResponse], None]],
    ) -> concurrent.futures.Future[PingResponse]: ...
class HelloService_Stub(HelloService):
    def __init__(self, rpc_channel: typing.Any) -> None: ...
    def Echo(self,
        rpc_controller: typing.Any,
        request: EchoRequest,
        done: typing.Optional[typing.Callable[[EchoResponse], None]],
    ) -> concurrent.futures.Future[EchoResponse]: ...
    def Ping(self,
        rpc_controller: typing.Any,
        request: PingRequest,
        done: typing.Optional[typing.Callable[[PingResponse], None]],
    ) -> concurrent.futures.Future[PingResponse]: ...